/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package iuGrafica;

import dominio.Administrador;
import dominio.EventosGenerales;
import dominio.Fachada;
import excepciones.MesaException;
import excepciones.UsuarioException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import observador.Observable;
import observador.Observador;

/**
 *
 * @author angel
 */
public class InicioAdministrador extends javax.swing.JFrame implements Observador {

    /**
     * Creates new form InicioAdministrador
     */
    private Administrador administrador;

    public InicioAdministrador(Administrador admin) {
        initComponents();
        setLocationRelativeTo(null);
        administrador = admin;
        setTitle("ADMINISTRADOR:" + administrador.getNombreCompleto().toUpperCase());
        mostrarMesas();
        mostrarTotalRecaudado();
        Fachada.getInstancia().agregarObservador(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDetalles = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMesas = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        detallesMesaSeleccionada = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();
        btnNuevaMesa = new javax.swing.JButton();
        tfCantidadJugadores = new javax.swing.JTextField();
        tfApuestaBase = new javax.swing.JTextField();
        tfPorcentaje = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campoMensaje = new javax.swing.JLabel();
        totalRecaudado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        btnDetalles.setText("Detalles");
        btnDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetallesActionPerformed(evt);
            }
        });

        tablaMesas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaMesas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        jScrollPane1.setViewportView(tablaMesas);

        jScrollPane2.setViewportView(detallesMesaSeleccionada);

        btnNuevaMesa.setText("Nueva Mesa");
        btnNuevaMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaMesaActionPerformed(evt);
            }
        });

        tfCantidadJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCantidadJugadoresActionPerformed(evt);
            }
        });

        tfApuestaBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfApuestaBaseActionPerformed(evt);
            }
        });

        jLabel1.setText("Máx Jugadores");

        jLabel2.setText("Apuesta Base");

        jLabel3.setText("Porcentaje");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfApuestaBase, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPorcentaje, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCantidadJugadores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(btnNuevaMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(campoMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfCantidadJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfApuestaBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnNuevaMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(campoMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        totalRecaudado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDetalles, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalRecaudado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane2)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 18, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(totalRecaudado, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDetalles, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void actualizar(Object evento, Observable origen) {
        if (evento.equals(EventosGenerales.Eventos.cambioListaTodasMesas)) {
            mostrarMesas();
            mostrarTotalRecaudado();
        }
    }

    private void mostrarMesas() {
        String[] columnas = {
            "NroMesa", "($)Apuesta Base", "Jug.Requeridos", "Jug.Actuales",
            "NroMano Actual", "($)Apostado", "(%)Comisión", "($)Recaudado", "Estado"
        };
        Object[][] datos = Fachada.getInstancia().listarTodasLasMesas();
        DefaultTableModel modeloTabla = new DefaultTableModel(datos, columnas) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        tablaMesas.setModel(modeloTabla);
        tablaMesas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tablaMesas.getTableHeader().setReorderingAllowed(false);
        tablaMesas.getTableHeader().setResizingAllowed(false);
        tablaMesas.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
    }

    private void obtenerYmostrarDetallesMesaSeleccionada() {
        int posicion = tablaMesas.getSelectedRow();
        if (posicion != -1) {
            int nroMesa = (int) tablaMesas.getValueAt(posicion, 0);
            ArrayList<String> detalles = Fachada.getInstancia().mostrarDetallesMesa(nroMesa);
            detallesMesaSeleccionada.setListData(detalles.toArray());
        }
    }

    private void crearMesa() throws MesaException, UsuarioException {
        try {
            String cantidadJugadoresText = tfCantidadJugadores.getText();
            String apuestaBaseText = tfApuestaBase.getText();
            String porcentajeText = tfPorcentaje.getText();

            if (cantidadJugadoresText.isEmpty() || apuestaBaseText.isEmpty() || porcentajeText.isEmpty()) {
                mostrarMensaje("Por favor, complete todos los campos.");
                return;
            }
            int cantJugadores = Integer.parseInt(cantidadJugadoresText);
            int apuestaBase = Integer.parseInt(apuestaBaseText);
            float comision = Float.parseFloat(porcentajeText);

            Fachada.getInstancia().crearMesa(apuestaBase, comision, cantJugadores);
        } catch (MesaException e) {
            mostrarMensaje(e.getMessage());
        }
    }

    public void mostrarTotalRecaudado() {
        int totalRecaudadoEnTodasLasMesas = Fachada.getInstancia().getTotalRecaudadoEnTodasLasMesas();
        String recaudado = "Total recaudado $" + totalRecaudadoEnTodasLasMesas;
        totalRecaudado.setText(recaudado);
    }

    public void mostrarMensaje(String mensaje) {
        campoMensaje.setText(mensaje);
    }

    private void btnDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetallesActionPerformed
        // TODO add your handling code here:
        obtenerYmostrarDetallesMesaSeleccionada();
    }//GEN-LAST:event_btnDetallesActionPerformed

    private void btnNuevaMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaMesaActionPerformed
        try {
            crearMesa();
        } catch (MesaException | UsuarioException ex) {
            Logger.getLogger(InicioAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnNuevaMesaActionPerformed

    private void tfCantidadJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCantidadJugadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCantidadJugadoresActionPerformed

    private void tfApuestaBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfApuestaBaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfApuestaBaseActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        Fachada.getInstancia().logoutAdmin(administrador.getCedula());
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalles;
    private javax.swing.JButton btnNuevaMesa;
    private javax.swing.JLabel campoMensaje;
    private javax.swing.JList detallesMesaSeleccionada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaMesas;
    private javax.swing.JTextField tfApuestaBase;
    private javax.swing.JTextField tfCantidadJugadores;
    private javax.swing.JTextField tfPorcentaje;
    private javax.swing.JLabel totalRecaudado;
    // End of variables declaration//GEN-END:variables

}
