/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package iuGrafica;

import vistas.LoginJugador;
import vistas.LoginAdministrador;

/**
 *
 * @author angel
 */
public class MenuInicio extends javax.swing.JFrame {

    /**
     * Creates new form MenuInicio
     */
    public MenuInicio() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Menu de Inicio");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jIngresar = new javax.swing.JMenu();
        itemAdmin = new javax.swing.JMenuItem();
        itemJugador = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jIngresar.setText("Ingresar");

        itemAdmin.setText("Administrador");
        itemAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAdminActionPerformed(evt);
            }
        });
        jIngresar.add(itemAdmin);

        itemJugador.setText("Jugador");
        itemJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemJugadorActionPerformed(evt);
            }
        });
        jIngresar.add(itemJugador);

        jMenuBar1.add(jIngresar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAdminActionPerformed
        // TODO add your handling code here:
        new LoginAdministrador(this,false).setVisible(true);
    }//GEN-LAST:event_itemAdminActionPerformed

    private void itemJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemJugadorActionPerformed
        // TODO add your handling code here:
        new LoginJugador(this,false).setVisible(true);
    }//GEN-LAST:event_itemJugadorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemAdmin;
    private javax.swing.JMenuItem itemJugador;
    private javax.swing.JMenu jIngresar;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
